import Head from "next/head";
import localFont from "next/font/local";
import styles from "@/styles/Home.module.scss";

const pretendard = localFont({
    src: "../fonts/Pretendard.woff2",
    variable: "--font-default",
    weight: "300",
});

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={`${styles.page} ${pretendard.variable}`}>
                <main className={styles.main}>
                    <h1>Hello, World!</h1>
                </main>
            </div>
        </>
    );
}
