import type { Metadata } from "next";
import React from "react";
import "./globals.scss";

export const metadata: Metadata = {
    title: process.env.FRONT_TITLE,
    description: "Generated by create next app"
};

export default function RootLayout({children}: Readonly<{children: React.ReactNode}>) {
    return (
        <html lang="en">
            <body>{children}</body>
        </html>
    );
}
