import Head from "next/head";
import localFont from "next/font/local";
import styles from "@/styles/Dir.module.scss";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
import { getData } from "@/util/route";
import { Render } from "@/components/Render";

const pretendard = localFont({
    src: "./fonts/Pretendard.woff2",
    variable: "--font-default",
    weight: "300",
});

export default function Root({ name, data }) {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={`${styles.page} ${pretendard.variable}`}>
                <Header name={name} />
                <main className={styles.main}>
                    <Render data={data.data} url={data.dir} />
                </main>
                <Footer />
            </div>
        </>
    );
}

export async function getServerSideProps() {
    const name = process.env.FRONT_TITLE;
    const port = process.env.SERVER_PORT;
    const data = await getData("/");

    return {
        props: { name, data, port }
    };
}
