import { Footer } from "@/components/Footer";
import "./globals.scss";

export const metadata = {
        title: "Create Next App",
        description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body>
				{children}
				<Footer />
			</body>
		</html>
	);
}
